name: testing

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  detect-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.get-modules.outputs.modules }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get GO modules
        uses: ci-space/go-modules-action@v0.1.0
        id: get-modules

  code-lint:
    name: code-lint
    runs-on: ubuntu-latest
    needs: detect-modules

    strategy:
      matrix:
        module: ${{ fromJSON(needs.detect-modules.outputs.modules) }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4 # action page: <https://github.com/actions/setup-go>
        with:
          go-version: stable
          cache-dependency-path: ${{ matrix.module.dir }}/go.sum

      - name: Install Go dependencies
        run: cd ${{ matrix.module.dir }} && go mod download

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: ${{ matrix.module.dir }}

  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4 # action page: <https://github.com/actions/setup-go>
        with:
          go-version: stable

      - name: Install Go dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
